// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTYiuULosQiI6w05ETW88mJvsx2xOzBBE',
    appId: '1:677074021795:web:8aa941cac6f7dee769fe16',
    messagingSenderId: '677074021795',
    projectId: 'flutter-5bv1',
    authDomain: 'flutter-5bv1.firebaseapp.com',
    storageBucket: 'flutter-5bv1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7Ng0A6fOKK_T1YG-y7o3P67wpWGmNkM',
    appId: '1:677074021795:android:3fa6833d959a7cec69fe16',
    messagingSenderId: '677074021795',
    projectId: 'flutter-5bv1',
    storageBucket: 'flutter-5bv1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMisVPCtSz7hzw9Zmo-324WSK5owztLuc',
    appId: '1:677074021795:ios:16e4790ecd1f4f7f69fe16',
    messagingSenderId: '677074021795',
    projectId: 'flutter-5bv1',
    storageBucket: 'flutter-5bv1.firebasestorage.app',
    iosBundleId: 'com.firebase5B.appFirebase5b',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMisVPCtSz7hzw9Zmo-324WSK5owztLuc',
    appId: '1:677074021795:ios:16e4790ecd1f4f7f69fe16',
    messagingSenderId: '677074021795',
    projectId: 'flutter-5bv1',
    storageBucket: 'flutter-5bv1.firebasestorage.app',
    iosBundleId: 'com.firebase5B.appFirebase5b',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTYiuULosQiI6w05ETW88mJvsx2xOzBBE',
    appId: '1:677074021795:web:939816e77448662669fe16',
    messagingSenderId: '677074021795',
    projectId: 'flutter-5bv1',
    authDomain: 'flutter-5bv1.firebaseapp.com',
    storageBucket: 'flutter-5bv1.firebasestorage.app',
  );
}
